import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const exercises = [
  // WARMUP - MOBILITY
  {
    id: "wm1",
    name: "Shoulder Circles & Arm Swings",
    description: "Dynamic arm circles forward and backward, followed by cross-body arm swings.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["shoulders", "mobility"],
  },
  {
    id: "wm2",
    name: "Wrist & Finger Warm-up",
    description: "Wrist circles, prayer stretches, finger extensions with rubber band.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["fingers", "wrists"],
  },
  {
    id: "wm3",
    name: "Hip Openers & Leg Swings",
    description: "Deep lunges, hip circles, lateral leg swings to open hips for high feet.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["hips", "legs"],
  },
  {
    id: "wm4",
    name: "Cat-Cow & Thoracic Rotations",
    description: "Spinal mobility: cat-cow on all fours, then thoracic rotation stretches.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["spine", "core"],
  },
  {
    id: "wm5",
    name: "Neck & Upper Trap Release",
    description:
      "Slow neck rolls, side tilts, and upper trapezius stretches to release tension before climbing.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 2,
    durationMax: 4,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["neck", "upper back"],
  },
  {
    id: "wm6",
    name: "Ankle & Toe Mobility",
    description:
      "Ankle rolls, toe spreads, and calf raises to prepare feet for precise footwork on small holds.",
    category: "warmup-mobility",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 2,
    durationMax: 4,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["ankles", "feet"],
  },

  // WARMUP - CLIMBING
  {
    id: "wc1",
    name: "Easy Traversing",
    description:
      "Traverse the wall at low height, focusing on smooth movement. Stay 2-3 grades below max.",
    category: "warmup-climbing",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 2,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["movement", "flow"],
  },
  {
    id: "wc2",
    name: "Progressive Ladder",
    description:
      "Climb 3-5 problems, each one grade harder. Start very easy, end 1-2 grades below max.",
    category: "warmup-climbing",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["progression", "warm-up"],
  },
  {
    id: "wc3",
    name: "Down-climb Practice",
    description: "Climb easy problems and reverse them. Great for control and warming up slowly.",
    category: "warmup-climbing",
    wallTypes: ["slab", "vertical"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 2,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["control", "technique"],
  },
  {
    id: "wc4",
    name: "Volume Warm-up",
    description:
      "Flash 5-8 problems well below your grade. Move steadily without stopping to build blood flow.",
    category: "warmup-climbing",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 10,
    durationMax: 20,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["blood flow", "activation"],
  },
  {
    id: "wc5",
    name: "Movement Isolation",
    description:
      "Pick one movement pattern (e.g. heel hooks, underclings) and practice it on easy terrain to activate it before projecting.",
    category: "warmup-climbing",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["movement prep", "activation"],
  },

  // TECHNIQUE
  {
    id: "t1",
    name: "Silent Feet",
    description:
      "Climb easy problems placing feet with zero noise. Focus on precision and awareness.",
    category: "technique",
    wallTypes: ["slab", "vertical"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["footwork", "precision"],
  },
  {
    id: "t2",
    name: "Hover Hands",
    description:
      "Before grabbing each hold, hover your hand 2cm away for 2 seconds. Builds intention.",
    category: "technique",
    wallTypes: ["slab", "vertical", "overhang"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["precision", "body awareness"],
  },
  {
    id: "t3",
    name: "Sticky Feet",
    description:
      "Once you place a foot, it cannot move. Commit to placements and read the wall ahead.",
    category: "technique",
    wallTypes: ["slab", "vertical"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["footwork", "reading"],
  },
  {
    id: "t4",
    name: "Flag & Twist Drills",
    description:
      "On moderate climbs, practice flagging and twisting into every move even when not required.",
    category: "technique",
    wallTypes: ["vertical", "overhang"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["balance", "efficiency"],
  },
  {
    id: "t5",
    name: "Slab Balance Walk",
    description:
      "Climb easy slab using only open hands. Focus on weight over feet and balance points.",
    category: "technique",
    wallTypes: ["slab"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 2,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["balance", "slab"],
  },
  {
    id: "t6",
    name: "Drop Knee Practice",
    description:
      "Find moderate overhang problems and practice turning hips using drop knees on every move.",
    category: "technique",
    wallTypes: ["overhang", "comp"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: ["knees"],
    focus: ["technique", "efficiency"],
  },
  {
    id: "t7",
    name: "Heel Hook Progressions",
    description:
      "On overhangs, seek out heel hook moves. Practice loading the heel actively and pulling with the hamstring.",
    category: "technique",
    wallTypes: ["overhang", "comp", "spray"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: ["knees"],
    focus: ["heel hooks", "body tension"],
  },
  {
    id: "t8",
    name: "Toe Hook Isolation",
    description:
      "Find problems requiring toe hooks. Focus on engaging the top of the foot and maintaining tension through the core.",
    category: "technique",
    wallTypes: ["overhang", "spray", "moonboard"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["toe hooks", "body tension"],
  },
  {
    id: "t9",
    name: "Pinch & Side-pull Drills",
    description:
      "Climb a circuit of moderate problems focusing exclusively on pinch and side-pull holds. Exaggerate hip position for each.",
    category: "technique",
    wallTypes: ["vertical", "overhang", "comp"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["pinch strength", "body position"],
  },
  {
    id: "t10",
    name: "Mantling & Pressing",
    description:
      "Practice pressing over the top of problems and mantling on high volumes. Essential for bouldering topouts.",
    category: "technique",
    wallTypes: ["slab", "vertical"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: ["shoulders"],
    focus: ["pressing", "topout"],
  },
  {
    id: "t11",
    name: "Quiet Hips Drill",
    description:
      "Climb moderate problems keeping hips perfectly square to the wall throughout. Then reclimb letting hips rotate naturally — feel the difference.",
    category: "technique",
    wallTypes: ["vertical", "slab"],
    levels: ["beginner", "intermediate"],
    durationMin: 8,
    durationMax: 12,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["hip position", "efficiency"],
  },
  {
    id: "t12",
    name: "No Thumb Climbing",
    description:
      "Climb easy problems using only four fingers (no thumb). Forces open-hand grip and foot reliance.",
    category: "technique",
    wallTypes: ["slab", "vertical"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["open hand", "footwork"],
  },

  // PROJECTING
  {
    id: "p1",
    name: "Project Burns",
    description:
      "Pick 1-2 problems at your limit. Work moves individually, then link sections. Full rest between attempts.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 40,
    intensity: 9,
    equipment: ["none"],
    injuryRisk: ["fingers", "shoulders"],
    focus: ["max strength", "problem solving"],
  },
  {
    id: "p2",
    name: "Beta Breakdown",
    description:
      "Read a hard problem from the ground. Plan every move before touching the wall. Then execute.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 7,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["reading", "strategy"],
  },
  {
    id: "p3",
    name: "Limit Moves",
    description: "Isolate the hardest move on your project. Repeat it 5-8 times with full rest.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 9,
    equipment: ["none"],
    injuryRisk: ["fingers", "shoulders"],
    focus: ["max strength", "power"],
  },
  {
    id: "p4",
    name: "Mirror Beta",
    description:
      "Watch another climber on your project and actively copy their exact sequence. Identify what differences exist in your attempts.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 20,
    intensity: 6,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["reading", "learning"],
  },
  {
    id: "p5",
    name: "Bottom-up Linking",
    description:
      "Link moves starting from the first hold, adding one more each attempt. Build toward a full send.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 40,
    intensity: 9,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["linking", "mental game"],
  },
  {
    id: "p6",
    name: "Top-down Linking",
    description:
      "Work a problem from the top down. Master the finish first, then add the preceding moves progressively.",
    category: "projecting",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 40,
    intensity: 9,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["redpoint strategy", "sections"],
  },

  // POWER
  {
    id: "pw1",
    name: "Campus Laddering",
    description: "Ladder up campus rungs: 1-2-3, 1-3-5, etc. Full rest between sets.",
    category: "power",
    wallTypes: ["any"],
    levels: ["advanced"],
    durationMin: 10,
    durationMax: 20,
    intensity: 9,
    equipment: ["campus-board"],
    injuryRisk: ["fingers", "shoulders", "elbows"],
    focus: ["contact strength", "power"],
  },
  {
    id: "pw2",
    name: "Dyno Practice",
    description: "Find or set dyno problems. Focus on explosive hip drive and coordination.",
    category: "power",
    wallTypes: ["comp", "overhang"],
    levels: ["intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 8,
    equipment: ["none"],
    injuryRisk: ["shoulders"],
    focus: ["explosiveness", "coordination"],
  },
  {
    id: "pw3",
    name: "Power Boulders",
    description:
      "Climb short, powerful problems (3-5 moves) near your limit. 3-5 min rest between.",
    category: "power",
    wallTypes: ["overhang", "comp", "spray"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 30,
    intensity: 8,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["power", "recruitment"],
  },
  {
    id: "pw4",
    name: "Dead Hangs to Big Moves",
    description:
      "Start each boulder with a dead hang of 3s on the first hold, then explode into the move. Trains contact strength from cold.",
    category: "power",
    wallTypes: ["overhang", "comp", "spray"],
    levels: ["intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 8,
    equipment: ["none"],
    injuryRisk: ["fingers", "shoulders"],
    focus: ["contact strength", "power"],
  },
  {
    id: "pw5",
    name: "One-Move Monsters",
    description:
      "Find or create single extremely hard moves. Attempt each move 5-8 times with full rest. Focus on maximum recruitment.",
    category: "power",
    wallTypes: ["overhang", "spray", "moonboard"],
    levels: ["advanced"],
    durationMin: 20,
    durationMax: 30,
    intensity: 10,
    equipment: ["none"],
    injuryRisk: ["fingers", "shoulders"],
    focus: ["max power", "recruitment"],
  },
  {
    id: "pw6",
    name: "Depth Jump Toe Hooks",
    description:
      "From a slight drop, land a large move onto a toe hook position. Builds reactive strength in leg-assisted pulling.",
    category: "power",
    wallTypes: ["overhang", "comp"],
    levels: ["advanced"],
    durationMin: 10,
    durationMax: 20,
    intensity: 8,
    equipment: ["none"],
    injuryRisk: ["knees", "ankles"],
    focus: ["reactive power", "coordination"],
  },

  // ENDURANCE
  {
    id: "e1",
    name: "4x4s",
    description:
      "Pick 4 problems 2-3 grades below max. Climb all 4 back-to-back, rest 4 min. Repeat 4 sets.",
    category: "endurance",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 35,
    intensity: 7,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["power endurance", "pump"],
  },
  {
    id: "e2",
    name: "ARC Training",
    description: "Climb continuously for 15-20 min at very easy grades. Stay below pump threshold.",
    category: "endurance",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["aerobic capacity", "recovery"],
  },
  {
    id: "e3",
    name: "Linked Circuits",
    description: "Link 3-4 easy-to-moderate problems into one continuous circuit. Rest and repeat.",
    category: "endurance",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["endurance", "flow"],
  },
  {
    id: "e4",
    name: "Interval Repeaters",
    description: "Climb for 1 min, rest for 1 min. Repeat 8-10 rounds on easy terrain.",
    category: "endurance",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["anaerobic endurance"],
  },
  {
    id: "e5",
    name: "Volume Day",
    description: "Flash as many easy-moderate problems as possible. Aim for 30-50 climbs.",
    category: "endurance",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 45,
    durationMax: 90,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["base volume", "movement mileage"],
  },
  {
    id: "e6",
    name: "Spray Wall Endurance",
    description:
      "Set a long sequence on the spray wall or connect several circuits. Climb for max moves before failure.",
    category: "endurance",
    wallTypes: ["spray"],
    levels: ["intermediate", "advanced"],
    durationMin: 20,
    durationMax: 35,
    intensity: 6,
    equipment: ["none"],
    injuryRisk: ["fingers"],
    focus: ["power endurance", "spray wall"],
  },
  {
    id: "e7",
    name: "Rest-step Overhang Laps",
    description:
      "Climb a moderate overhang problem, find a rest position, recover partially, then continue. Repeat 4-6 laps.",
    category: "endurance",
    wallTypes: ["overhang", "comp"],
    levels: ["intermediate", "advanced"],
    durationMin: 15,
    durationMax: 25,
    intensity: 6,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["on-wall recovery", "endurance"],
  },

  // FINGER STRENGTH
  {
    id: "f1",
    name: "Hangboard Repeaters",
    description: "7s hang / 3s rest × 6 reps. 3 min between sets. Half crimp on medium edge.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 20,
    intensity: 8,
    equipment: ["hangboard"],
    injuryRisk: ["fingers"],
    focus: ["finger strength", "tendons"],
  },
  {
    id: "f2",
    name: "Max Hangs",
    description: "10s max effort hang with added weight. 3 min rest × 5 sets. Half crimp only.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["advanced"],
    durationMin: 15,
    durationMax: 20,
    intensity: 9,
    equipment: ["hangboard"],
    injuryRisk: ["fingers"],
    focus: ["max finger strength"],
  },
  {
    id: "f3",
    name: "Easy Hangs (Warm-up)",
    description: "Light hangs on large edges: 10s on, 10s off × 5. No added weight.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 3,
    equipment: ["hangboard"],
    injuryRisk: [],
    focus: ["finger warm-up"],
  },
  {
    id: "f4",
    name: "Open Hand Isolations",
    description:
      "Hang on medium pockets and slopers using open hand only. 3 × 10s hangs with 2 min rest.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 10,
    durationMax: 15,
    intensity: 7,
    equipment: ["hangboard"],
    injuryRisk: ["fingers"],
    focus: ["open hand", "tendon health"],
  },
  {
    id: "f5",
    name: "Sloper Hangs",
    description: "Hang on sloped holds. 3 × 10s. Focus on wrist, elbow, and shoulder alignment.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 8,
    durationMax: 12,
    intensity: 7,
    equipment: ["hangboard"],
    injuryRisk: ["fingers", "wrists"],
    focus: ["sloper strength", "contact force"],
  },
  {
    id: "f6",
    name: "Crimp Strength Blocks",
    description: "Work half-crimp on a small edge (20mm). 5s hang / 55s rest × 10 sets.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["advanced"],
    durationMin: 12,
    durationMax: 18,
    intensity: 9,
    equipment: ["hangboard"],
    injuryRisk: ["fingers"],
    focus: ["crimp strength", "max load"],
  },
  {
    id: "f7",
    name: "Pinch Block Squeezes",
    description:
      "Hold a pinch block for 3 × 30s squeezes. Builds thumb opposition and pinch force.",
    category: "finger-strength",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: ["thumbs"],
    focus: ["pinch", "thumb strength"],
  },

  // CORE
  {
    id: "c1",
    name: "Hollow Body Hold",
    description: "30s hold × 3 sets. Arms overhead, legs extended, lower back flat.",
    category: "core",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 5,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["core tension", "stability"],
  },
  {
    id: "c2",
    name: "Hanging Leg Raises",
    description: "Hang from bar. Raise legs to 90° (or toes to bar). 3 × 8-12 reps.",
    category: "core",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 6,
    equipment: ["pull-up-bar"],
    injuryRisk: ["shoulders"],
    focus: ["core", "hip flexors"],
  },
  {
    id: "c3",
    name: "Plank Variations",
    description: "Front plank 45s, side plank 30s each side. 2-3 rounds.",
    category: "core",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["core stability"],
  },
  {
    id: "c4",
    name: "L-sit Hold",
    description: "Hang from a pull-up bar and hold an L-sit with legs extended. 3 × 15-30s.",
    category: "core",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 7,
    equipment: ["pull-up-bar"],
    injuryRisk: ["shoulders"],
    focus: ["core compression", "hip flexors"],
  },
  {
    id: "c5",
    name: "Front Lever Progressions",
    description: "Tuck → advanced tuck → straddle → full. Hold 3 × 5-10s.",
    category: "core",
    wallTypes: ["any"],
    levels: ["intermediate", "advanced"],
    durationMin: 8,
    durationMax: 15,
    intensity: 8,
    equipment: ["pull-up-bar"],
    injuryRisk: ["shoulders"],
    focus: ["body tension", "straight arm strength"],
  },
  {
    id: "c6",
    name: "Arch Body Rocks",
    description: "Alternate between hollow body and arch body positions. 3 × 15 reps.",
    category: "core",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["core control", "body tension"],
  },
  {
    id: "c7",
    name: "Typewriter Pull-ups",
    description: "Pull up to one side, traverse the bar, lower on the other side. 3 × 5 reps.",
    category: "core",
    wallTypes: ["any"],
    levels: ["advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 8,
    equipment: ["pull-up-bar"],
    injuryRisk: ["shoulders"],
    focus: ["core", "lat strength"],
  },

  // ANTAGONIST
  {
    id: "a1",
    name: "Push-ups",
    description: "3 × 10-15 push-ups. Slow and controlled. Balance out pulling muscles.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 4,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["chest", "shoulders", "balance"],
  },
  {
    id: "a2",
    name: "Reverse Wrist Curls",
    description: "Light dumbbell or band. 3 × 15 wrist extensions. Prevent elbow issues.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 2,
    equipment: ["resistance-bands"],
    injuryRisk: [],
    focus: ["forearm balance", "elbows"],
  },
  {
    id: "a3",
    name: "External Rotation",
    description: "Band external rotations for rotator cuff health. 3 × 12 each arm.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 2,
    equipment: ["resistance-bands"],
    injuryRisk: [],
    focus: ["shoulders", "prehab"],
  },
  {
    id: "a4",
    name: "Dumbbell Tricep Extensions",
    description: "Overhead tricep extension or skullcrusher. 3 × 12 at light weight.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 3,
    equipment: ["none"],
    injuryRisk: ["elbows"],
    focus: ["triceps", "elbow health"],
  },
  {
    id: "a5",
    name: "Scapular Retractions",
    description:
      "Band pull-aparts and face pulls. 3 × 15. Counteracts protracted shoulder posture.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 2,
    equipment: ["resistance-bands"],
    injuryRisk: [],
    focus: ["scapula", "posture"],
  },
  {
    id: "a6",
    name: "Prone Y-T-W Raises",
    description: "Lying face down, raise arms in Y, T, then W positions. 2 × 10 each.",
    category: "antagonist",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 2,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["scapula", "shoulder health"],
  },

  // COOLDOWN
  {
    id: "cd1",
    name: "Forearm & Finger Stretches",
    description: "Prayer stretch, reverse prayer, individual finger stretches. Hold 20-30s each.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["fingers", "forearms"],
  },
  {
    id: "cd2",
    name: "Shoulder & Back Stretch",
    description: "Cross-body shoulder stretch, doorway chest opener, child's pose.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["shoulders", "back"],
  },
  {
    id: "cd3",
    name: "Hip & Leg Stretch",
    description: "Pigeon stretch, hamstring stretch, quad stretch. Hold 30s each side.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["hips", "legs"],
  },
  {
    id: "cd4",
    name: "Full Body Cooldown Flow",
    description:
      "Gentle yoga-inspired flow: cat-cow, downward dog, child's pose, seated forward fold.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 10,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["full body", "relaxation"],
  },
  {
    id: "cd5",
    name: "Theraband Finger Flexion",
    description: "Light resistance finger curls to flush forearms and aid recovery.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["resistance-bands"],
    injuryRisk: [],
    focus: ["fingers", "recovery"],
  },
  {
    id: "cd6",
    name: "Wrist Flexor Deep Stretch",
    description: "Hold a full wrist extension against a flat surface for 45s. Repeat in reverse.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 3,
    durationMax: 5,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["wrists", "forearms"],
  },
  {
    id: "cd7",
    name: "Chest & Lat Opener",
    description: "Use a foam roller or doorway to open pecs and lats. 3 × 30s each side.",
    category: "cooldown",
    wallTypes: ["any"],
    levels: ["beginner", "intermediate", "advanced"],
    durationMin: 5,
    durationMax: 8,
    intensity: 1,
    equipment: ["none"],
    injuryRisk: [],
    focus: ["chest", "lats", "posture"],
  },
];

async function main() {
  console.log("Seeding exercises…");
  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { id: ex.id },
      update: ex,
      create: ex,
    });
  }
  console.log(`Seeded ${exercises.length} exercises.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
