/**
 * Generates D1 seed SQL for the exercise catalog (+ its join tables) from the
 * single source of truth in backend/prisma/seed.ts.
 *
 *   bun run scripts/gen-seed-sql.ts > backend/prisma/seed.sql
 *   wrangler d1 execute zoneit --remote --file backend/prisma/seed.sql
 *
 * Note: the glossary `Term` rows live inside seed.ts's main() and are carried
 * over by the production data migration (scripts/pg-to-d1.ts). For a brand-new
 * environment without a source DB, seed terms via that same SQL approach.
 */
import { exercises } from "../backend/prisma/seed";

type Exercise = (typeof exercises)[number] & {
  defaultSets?: number | null;
  defaultReps?: number | null;
  injuryRisk: string[];
  equipment: string[];
  wallTypes: string[];
  levels: string[];
  focus: string[];
};

const sq = (s: string): string => `'${s.replace(/'/g, "''")}'`;
const num = (n: number | null | undefined): string => (n == null ? "NULL" : String(n));

const lines: string[] = [
  "-- Auto-generated by scripts/gen-seed-sql.ts — do not edit by hand.",
  "-- Exercise catalog + join tables for Cloudflare D1 (SQLite).",
  "",
];

// Idempotent: clear the catalog first (join tables cascade, but be explicit).
for (const t of [
  "ExerciseWallType",
  "ExerciseLevel",
  "ExerciseEquipment",
  "ExerciseInjuryRisk",
  "ExerciseFocus",
  "Exercise",
]) {
  lines.push(`DELETE FROM "${t}";`);
}
lines.push("");

for (const exRaw of exercises as Exercise[]) {
  const ex = exRaw;
  lines.push(
    `INSERT INTO "Exercise" ("id","name","description","category","durationMin","durationMax","intensity","defaultSets","defaultReps") VALUES (` +
      [
        sq(ex.id),
        sq(ex.name),
        sq(ex.description),
        sq(ex.category),
        num(ex.durationMin),
        num(ex.durationMax),
        num(ex.intensity),
        num(ex.defaultSets),
        num(ex.defaultReps),
      ].join(",") +
      ");",
  );

  const joins: [string, string[]][] = [
    ["ExerciseWallType", ex.wallTypes],
    ["ExerciseLevel", ex.levels],
    ["ExerciseEquipment", ex.equipment],
    ["ExerciseInjuryRisk", ex.injuryRisk],
    ["ExerciseFocus", ex.focus],
  ];
  for (const [table, values] of joins) {
    for (const value of values ?? []) {
      lines.push(
        `INSERT INTO "${table}" ("exerciseId","value") VALUES (${sq(ex.id)},${sq(value)});`,
      );
    }
  }
}

lines.push("");
lines.push(
  `INSERT INTO "AppConfig" ("key","value","updatedAt") VALUES ('testingMode','false',CURRENT_TIMESTAMP) ON CONFLICT("key") DO NOTHING;`,
);

process.stdout.write(lines.join("\n") + "\n");
