/**
 * One-time data migration: source PostgreSQL (old Railway schema) -> Cloudflare
 * D1 seed SQL. Transforms the Postgres array columns into join-table rows and
 * keeps the JSON(b) columns as JSON-encoded TEXT.
 *
 *   SOURCE_DATABASE_URL=postgres://... bun run scripts/pg-to-d1.ts > seed-data.sql
 *   wrangler d1 execute zoneit --remote --file seed-data.sql
 *
 * The script prints source row counts to STDERR — compare them against the D1
 * counts after import (the cutover gate). SQL goes to STDOUT.
 *
 * Run a backup (pg_dump) BEFORE relying on this, and rehearse against a
 * throwaway D1 first.
 */
import { Client } from "pg";

const SOURCE = process.env.SOURCE_DATABASE_URL;
if (!SOURCE) {
  console.error("SOURCE_DATABASE_URL is required (the Railway Postgres URL).");
  process.exit(1);
}

// ─── SQL literal helpers ──────────────────────────────────────────────────────

const sq = (s: string): string => `'${s.replace(/'/g, "''")}'`;

/** Format a JS value (as returned by node-postgres) into a SQLite literal,
 *  matching how Prisma stores each type on D1. */
function val(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "1" : "0"; // SQLite bool = INTEGER 0/1
  if (typeof v === "number") return String(v);
  if (v instanceof Date) return `'${v.toISOString().replace("Z", "+00:00")}'`; // Prisma DateTime
  if (typeof v === "string") return sq(v);
  return sq(JSON.stringify(v)); // jsonb object/array -> JSON TEXT
}

const out: string[] = [];
const emit = (line: string) => out.push(line);

/** Emit an INSERT for `table` taking `columns` from `row` (in order). */
function insert(table: string, columns: string[], row: Record<string, unknown>): void {
  const cols = columns.map((c) => `"${c}"`).join(",");
  const vals = columns.map((c) => val(row[c])).join(",");
  emit(`INSERT INTO "${table}" (${cols}) VALUES (${vals});`);
}

/** Emit join-table rows for a former Postgres array column. */
function insertJoin(
  table: string,
  ownerCol: string,
  ownerId: string,
  valueCol: string,
  values: unknown[] | null,
): void {
  for (const value of values ?? []) {
    emit(
      `INSERT INTO "${table}" ("${ownerCol}","${valueCol}") VALUES (${sq(ownerId)},${val(value)});`,
    );
  }
}

// ─── Migration ────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const pg = new Client({ connectionString: SOURCE });
  await pg.connect();

  const counts: Record<string, number> = {};
  const rowsOf = async (sql: string): Promise<Record<string, unknown>[]> => (await pg.query(sql)).rows;

  emit("-- Auto-generated by scripts/pg-to-d1.ts — one-time PG -> D1 migration.");
  emit("PRAGMA foreign_keys=OFF;");
  emit("");

  // Parents first so foreign keys are satisfied even if enforcement is on.

  // Users
  const users = await rowsOf(`SELECT * FROM "User"`);
  counts.User = users.length;
  for (const u of users) {
    insert(
      "User",
      [
        "id", "googleId", "email", "name", "picture", "passwordHash", "age",
        "weightKg", "heightCm", "restTimeSeconds", "isVip", "createdAt", "updatedAt",
      ],
      u,
    );
  }

  // Exercises (+ array columns -> join tables)
  const exercises = await rowsOf(`SELECT * FROM "Exercise"`);
  counts.Exercise = exercises.length;
  for (const ex of exercises) {
    insert(
      "Exercise",
      ["id", "name", "description", "category", "durationMin", "durationMax", "intensity", "defaultSets", "defaultReps"],
      ex,
    );
    const id = ex.id as string;
    insertJoin("ExerciseWallType", "exerciseId", id, "value", ex.wallTypes as unknown[]);
    insertJoin("ExerciseLevel", "exerciseId", id, "value", ex.levels as unknown[]);
    insertJoin("ExerciseEquipment", "exerciseId", id, "value", ex.equipment as unknown[]);
    insertJoin("ExerciseInjuryRisk", "exerciseId", id, "value", ex.injuryRisk as unknown[]);
    insertJoin("ExerciseFocus", "exerciseId", id, "value", ex.focus as unknown[]);
  }

  // Folders (before Workouts)
  const folders = await rowsOf(`SELECT * FROM "Folder"`);
  counts.Folder = folders.length;
  for (const f of folders) {
    insert("Folder", ["id", "name", "userId", "order", "createdAt", "updatedAt"], f);
  }

  // Workouts (jsonb -> TEXT)
  const workouts = await rowsOf(`SELECT * FROM "Workout"`);
  counts.Workout = workouts.length;
  for (const w of workouts) {
    insert(
      "Workout",
      ["id", "name", "userId", "folderId", "sessionInput", "generatedSession", "createdAt", "updatedAt"],
      w,
    );
  }

  // Session logs (jsonb -> TEXT, nullable)
  const sessionLogs = await rowsOf(`SELECT * FROM "SessionLog"`);
  counts.SessionLog = sessionLogs.length;
  for (const s of sessionLogs) {
    insert(
      "SessionLog",
      ["id", "userId", "workoutId", "sessionTitle", "sessionSubtitle", "startedAt", "durationSeconds", "exerciseCount", "notes", "exercises", "createdAt"],
      s,
    );
  }

  // Programs (days jsonb -> TEXT)
  const programs = await rowsOf(`SELECT * FROM "Program"`);
  counts.Program = programs.length;
  for (const p of programs) {
    insert(
      "Program",
      ["id", "userId", "name", "description", "type", "lengthWeeks", "days", "createdAt", "updatedAt"],
      p,
    );
  }

  // Program progress (+ completedDays int[] -> join table)
  const progress = await rowsOf(`SELECT * FROM "ProgramProgress"`);
  counts.ProgramProgress = progress.length;
  for (const pr of progress) {
    insert(
      "ProgramProgress",
      ["id", "userId", "programId", "week", "completedCount", "startedAt", "updatedAt"],
      pr,
    );
    insertJoin(
      "ProgramProgressCompletedDay",
      "progressId",
      pr.id as string,
      "day",
      pr.completedDays as unknown[],
    );
  }

  // Shared workouts (jsonb -> TEXT)
  const shared = await rowsOf(`SELECT * FROM "SharedWorkout"`);
  counts.SharedWorkout = shared.length;
  for (const s of shared) {
    insert(
      "SharedWorkout",
      ["id", "code", "createdById", "workoutId", "workoutName", "sessionInput", "generatedSession", "expiresAt", "importCount", "createdAt"],
      s,
    );
  }

  // App config
  const appConfig = await rowsOf(`SELECT * FROM "AppConfig"`);
  counts.AppConfig = appConfig.length;
  for (const a of appConfig) insert("AppConfig", ["key", "value", "updatedAt"], a);

  // Promo codes
  const promoCodes = await rowsOf(`SELECT * FROM "PromoCode"`);
  counts.PromoCode = promoCodes.length;
  for (const p of promoCodes) insert("PromoCode", ["id", "code", "usedAt", "usedBy", "createdAt"], p);

  // Terms
  const terms = await rowsOf(`SELECT * FROM "Term"`);
  counts.Term = terms.length;
  for (const t of terms) insert("Term", ["id", "term", "definition", "letter"], t);

  emit("");
  emit("PRAGMA foreign_keys=ON;");

  await pg.end();

  process.stdout.write(out.join("\n") + "\n");

  console.error("\nSource row counts (verify these match D1 after import):");
  for (const [table, n] of Object.entries(counts)) {
    console.error(`  ${table.padEnd(28)} ${n}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
